name: Build for Release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"
      - name: checkout repo
        uses: actions/checkout@main
      - uses: ko-build/setup-ko@v0.6
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: piny940
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build application
        run: make build.push IMAGE=ghcr.io/piny940/external-dns
